# VittoriaDB RAG Web UI - Cloud Deployment
# Uses pre-built images from GitHub Container Registry for faster deployment

services:
  # VittoriaDB Server (from ghcr.io)
  vittoriadb:
    image: ghcr.io/antonellof/vittoriadb:v0.5.0
    ports:
      - "8080:8080"
    environment:
      - VITTORIADB_HOST=0.0.0.0
      - VITTORIADB_PORT=8080
      - VITTORIADB_DATA_DIR=/data
      - VITTORIADB_LOG_LEVEL=INFO
      # v0.5.0 Performance optimizations
      - VITTORIA_PERF_ENABLE_SIMD=true
      - VITTORIA_SEARCH_PARALLEL_MAX_WORKERS=16
      - VITTORIA_PERF_IO_USE_MEMORY_MAP=true
      - VITTORIA_SEARCH_CACHE_ENABLED=true
      - VITTORIA_SEARCH_CACHE_SIZE=1000
    volumes:
      - vittoriadb_data:/data
    networks:
      - vittoriadb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # VittoriaDB RAG Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITTORIADB_URL=http://vittoriadb:8080
      - OLLAMA_URL=${OLLAMA_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=8501
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    volumes:
      - ./uploads:/app/uploads  # File uploads
      - backend_logs:/app/logs  # Backend logs
    networks:
      - vittoriadb-network
    depends_on:
      vittoriadb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8501}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:8501}
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - vittoriadb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Ollama service for local ML models
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - vittoriadb-network
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Uncomment for GPU support on cloud instances
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  vittoriadb-network:
    driver: bridge
    name: vittoriadb-network

volumes:
  vittoriadb_data:
    driver: local
    name: vittoriadb_data
  ollama_data:
    driver: local
    name: ollama_data
  backend_logs:
    driver: local
    name: backend_logs
